# Delivery workflow for automatic version tagging and release management
name: Delivery

# Only trigger on direct pushes to main branch, ignoring tag pushes
on:
  push:
    branches: [main]
    tags-ignore: ['**']

# Grant permissions to modify repository contents (needed for tag creation)
permissions:
  contents: write

jobs:
  # Job to create a new pre-release tag for versioning
  update-tag:
    runs-on: ubuntu-24.04

    steps:
    # Check out the repository with full history for proper version calculation
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Create a new pre-release tag based on semantic versioning
    - name: Create new pre-release tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: '_NONE_' 
        pre_release_branches: main
        default_prerelease_bump: prerelease
        append_to_pre_release_tag: pre
        tag_prefix: v