name: Pre-release

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy-rc:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(git tag --list --sort=-v:refname | head -n1)
          echo "latest=$latest_tag" >> $GITHUB_OUTPUT

      - name: Generate pre-release tag
        id: prerelease
        run: |
          base_version=$(echo "${{ steps.get_tag.outputs.latest }}" | sed 's/-.*//')
          prerelease_base="${base_version}-rc"
          
          rc_tags=$(git tag --list | grep "${prerelease_base}.*" | wc -l)
          tags=$(git tag --list | grep "${base_version}" | wc -l)
          
          IFS='.' read -r major minor patch <<< "$(echo "$base_version" | sed 's/^v//')" 
          
          if [[ tags -gt $rc_tags ]]; then
            echo "There are more tags than rc tags for the same version, it means that this version was already released."
            new_tag="v$major.$minor.$((patch+1))-rc.0"
          else
            new_tag="${prerelease_base}.$((rc_tags))"
          fi
          
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create pre-release tag
        run: |
          git tag "${{ steps.prerelease.outputs.new_tag }}"
          git push origin "${{ steps.prerelease.outputs.new_tag }}"

      # Enables the runner to emulate different architectures
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Creates a builder instance capable of multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=false
            type=raw,value=latest-rc
            type=raw,value=${{ steps.prerelease.outputs.new_tag }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push docker image
        uses: docker/build-push-action@v5
        with:
          build-args: VERSION=${{ steps.prerelease.outputs.new_tag }}
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max,image-manifest=true

      - name: Create pre-release
        id: create_prerelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.prerelease.outputs.new_tag }}
          prerelease: true